reddit:
  subreddits:
    - beer
    - nonalcoholic
    - stopdrinking
x:
  search_terms:
    - non-alcoholic beer
    - "NA beer"
    - hopwater
  tweet_language: en
  days_back: 7
  max_items: 150
  sort: Latest   # or Top
news_rss:
  - https://www.bevnet.com/feed/
  - https://www.brewersassociation.org/feed/
  - https://www.prnewswire.com/rss/consumer-products-retail.xml
trends_terms:
  - non alcoholic beer
  - NA beer
  - alcohol free beer
  - 0.0 beer
  - hop water
trends_geo: US
trends_time_range: "now 7-d"
